"""
Figurize
========

For each image in an article generated by pelican, this plugin will...

1. Wrap it, and the subsequent paragraph, in a `<figure>` tag.
2. Change the tag of the subsequent paragraph to `<figcaption>`.
"""

from pelican import signals
from bs4 import BeautifulSoup

def figurize(content):
    soup = BeautifulSoup(content._content, 'html.parser')

    for img in soup.find_all('img'):
        if img is not None:
            figure = img.parent
            figcaption = soup.new_tag('figcaption')
            for el in list(img.next_siblings):
                figcaption.append(el)
            img.insert_after(figcaption)
            figure.name = 'figure'

    content._content = soup.decode()

def register():
    signals.content_object_init.connect(figurize)
